Sprint1
ClevertecFrontendLab/sprint1-DaryaEnina pull request #1
Opened 2023-01-31 21:45 UTC by DaryaEnina

2023-01-31 21:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675201826/content-window.png)

2023-01-31 22:08 UTC, klichkovskiy requested changes
Исправь 2 мелких недочета) Хорошая работа!

2023-01-31 22:08 UTC, klichkovskiy commented on src/index.js
> +          {/* <Route path={profile} element={<ProfilePage />} /> */}
Удали закомментированный код

2023-01-31 22:08 UTC, klichkovskiy commented on src/components/nav/nav.tsx
> +        <NavLink
![image](https://user-images.githubusercontent.com/62481116/215894328-dcbbfb93-f30c-441c-b939-ed6c8efa4e6b.png)
Активна когда выбран любой жанр или "Все книги"

2023-02-01 15:27 UTC, DaryaEnina commented on src/components/nav/nav.tsx
> +        <NavLink
Исправлено
![image](https://user-images.githubusercontent.com/78152480/216085969-f26e7350-ab64-4e58-afab-7e04e04e6020.png)

2023-02-01 15:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 66.66666666666666%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/book-page%20768px.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/content-list%20768px.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DaryaEnina/1675265422/content-window%20768px.png)

2023-02-01 15:45 UTC, Ivan6813 requested changes

2023-02-01 15:45 UTC, Ivan6813 commented on src/components/books/index.tsx
> +          listType={listType}
кажется эта кнопка не на своем месте, сверься с макетом


![msedge_3q2hPQcHto](https://user-images.githubusercontent.com/79784960/216090713-ed42c7cc-7682-4bd4-9874-dd7c082155c6.png)

2023-02-01 15:45 UTC, Ivan6813 commented on src/components/books/index.tsx
> +        />
карточки должны иметь одинаковую ширину

![msedge_lFT8vo3eot](https://user-images.githubusercontent.com/79784960/216091116-385536cd-11dc-4fb0-be23-c9f31c4d2b53.png)

2023-02-01 15:45 UTC, Ivan6813 commented on src/components/books/index.tsx
> +  </div>
и проверь почему у тебя нет десктопных скриншотов. Мобильные и планшетные есть, а десктопных не вижу

2023-02-01 16:07 UTC, DaryaEnina commented on src/components/books/index.tsx
> +  </div>
Запустила занова тесты и сделала скриншоты

2023-02-01 16:07 UTC, DaryaEnina commented on src/components/books/index.tsx
> +        />
Исправлено
![image](https://user-images.githubusercontent.com/78152480/216097007-64656c15-9a09-4772-b637-819a842f44ac.png)

2023-02-01 16:07 UTC, DaryaEnina commented on src/components/books/index.tsx
> +          listType={listType}
Исправлено
![image](https://user-images.githubusercontent.com/78152480/216096799-3ffd2c9c-d3cf-472d-ae97-8c742ac8ac07.png)

2023-02-01 16:20 UTC, klichkovskiy approved these changes

2023-02-01 16:43 UTC, Ivan6813 approved these changes

2023-02-01 16:44 UTC, merged